version: '3.1'
services:
  spboot-rabbitmq:
    image: rabbitmq:3.11-management
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      - RABBITMQ_DEFAULT_USER=12345
      - RABBITMQ_DEFAULT_PASS=12345